clear;
make;
clear;
java -cp lib/antlr.jar:classes/ Micro input/test_combination.micro > input/test_combination.out;
java -cp lib/antlr.jar:classes/ Micro input/test_expr.micro > input/test_expr.out;
java -cp lib/antlr.jar:classes/ Micro input/test_mult.micro > input/test_mult.out;
diff input/test_combination.out output/test_combination.out > diffs/test_combination.txt || exit 0;
diff input/test_expr.out output/test_expr.out > diffs/test_expr.txt || exit 0;
diff input/test_mult.out output/test_mult.out > diffs/test_mult.txt || exit 0;
cat diffs/test_combination.txt;
cat diffs/test_expr.txt;
cat diffs/test_mult.txt;
