clear;
make;
clear;
java -cp lib/antlr.jar:classes/ Micro input/test_adv.micro > input/test_adv.out;
java -cp lib/antlr.jar:classes/ Micro input/test_if.micro > input/test_if.out;
java -cp lib/antlr.jar:classes/ Micro input/test_while.micro > input/test_while.out;
java -cp lib/antlr.jar:classes/ Micro input/step4_testcase.micro > input/step4_testcase.out;
java -cp lib/antlr.jar:classes/ Micro input/step4_testcase2.micro > input/step4_testcase2.out;
rm diffs/*;
diff input/test_adv.out output/test_adv.out > diffs/test_adv.txt || exit 0;
diff input/test_if.out output/test_if.out > diffs/test_if.txt || exit 0;
diff input/test_while.out output/test_while.out > diffs/test_while.txt || exit 0;
diff input/step4_testcase.out output/step4_testcase.out > diffs/step4_testcase.txt || exit 0;
diff input/step4_testcase2.out output/step4_testcase2.out > diffs/step4_testcase2.txt || exit 0;
cat diffs/test_adv.txt;
cat diffs/test_if.txt;
cat diffs/test_while.txt;
cat diffs/step4_testcase.txt;
cat diffs/step4_testcase2.txt;
